trigger:
  - main
pool: 'default'

stages:
  stage: "Maven_Build"
  jobs:
    job:  "build"
    steps:
      - task: Maven@4
        inputs:
          mavenPOMFile: 'pom.xml'
          goals: 'package'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'


