trigger:
  - main
pool: 'default'

variables:
  - group: Sonar-Cloud-Token

stages:
  - stage: "Maven_Build"
    jobs:
      - job:  "build"
        steps:

          - task: SonarCloudPrepare@3
            displayName: Prepare Sonar Cloud Analysis
            inputs:
              SonarCloud: 'Sonar-Cloud-Token'
              organization: 'opsbynikhil'
              scannerMode: 'Other'
              projectKey: 'opsbyNikhil_spring-petclinic'
              projectName: 'petclinic'

          - task: Maven@4
            displayName: Prepare maven 
            inputs:
              mavenPOMFile: 'pom.xml'
              goals: 'package sonar:sonar'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'

          - task: Maven@4
            displayName: Run Sonar Cloud Analysis
            inputs:
              mavenPOMFile: 'pom.xml'
              goals: "sonar:sonar"
              options:  "-Dsonar.token=$(Sonar-Cloud-Token)
                         -Dsonar.projectKey=opsbyNikhil_spring-petclinic
                         -Dsonar.organization= opsbynikhil"
              publishJUnitResults: false

          - task: SonarCloudPublish@3
            inputs:
              pollingTimeoutSec: '300'
 






