trigger:
  - main
pool: 'Default'

stages:
  - stage: 'build-stage'
    jobs:
      - job:  "maven"
        steps:
          - task: Maven@4
            inputs:  
              mavenPOMFile: 'pom.xml'
              goals:  'package'
              publishJUnitResults = true
              testresultsFiles: '**/surefire-reports/TEST-*.xml'