apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: spc-dev
  labels:
    env: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi  
  storageClassName: "my-spc-pvc"
