apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-spc-pvc-storage
  namespace: spc-dev
  labels:
    env: dev
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3