name: GitHub-actions

on:
  push:
    branchs: 
      - main

jobs:
  build:
    name: my-spc
    runs-on: self-hosted

    steps:
      - name: gitcheckout
        uses: actions/checkout@v6
    
      - name: maven-build
        uses: 'mvn package' 