name: GitHub-actions

on:
  push:
    branchs: 
      - main

jobs:
  build:
    name: my-spc
    runs-on: self-hosted

    steps:
      - name: gitcheckout
        uses: actions/checkout@v6
    
      - name: maven-build
        run: 'mvn package' 

      - name: sonar-scan
        run: |
          mvn package sonar:sonar \
          -Dsonar.projectKey=opsbyNikhil_spring-petclinic \
          -Dsonar.organization=opsbynikhil \
          -Dsonar.host.url=https://sonarcloud.io/ \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}