name: Git-Hub Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    name: my-spc
    runs-on: self-hosted

    steps:
      - name: Git-Checkout
        uses: actions/checkout@v6

      - name: Build-Maven
        run: "mvn package"

